
### Find All Accounts

GET http://localhost:8080/atm/

### Create New Account

POST http://localhost:8080/atm/ HTTP/1.1 
content-type: application/json

{
    "id" : 17, 
    "owner" : "zwr", 
    "balance" : 98
}
