### CRUD API ExpressJs

GET http://localhost:3000/

###

POST http://localhost:3000/ HTTP/1.1 
content-type: application/json

{
    "id" : 12, 
    "name" : "", 
    "category" : "rrr", 
    "price" : 45.90
}

###

PUT http://localhost:3000/ HTTP/1.1 content-type: application/json

{
"id" : 12, "name" : "pqr", "category" : "lmn", "price" : 489.90
}

###

DELETE http://localhost:3000/ HTTP/1.1