
### CRUD API For Items

GET http://localhost:8080/item/

###

POST http://localhost:8080/item/ HTTP/1.1 
content-type: application/json

{
   "id" : 12,
   "name" : "abc",
   "category" : "rrr",
   "price" : 45.90
}

###

PUT http://localhost:8080/item/ HTTP/1.1 
content-type: application/json

{
   "id" : 12,
   "name" : "pqr",
   "category" : "lmn",
   "price" : 489.90
}

####

DELETE http://localhost:8080/item/12 HTTP/1.1 